### ISSUE TITLE
Github Page 주소를 README.md 안에 데모로 링크

### ISSUE THREAD

**Issue by ryuheechul** [SDuck4/type-hangul#6]
하면 처음 이 프로젝트를 방문하는 사람들에게 이 프로젝트가 무엇인지 이걸 사용해서 어떤 효과를 얻을 수 있는지 빠르게 전달 가능 할거에요.

**Comment by SDuck4** [comment]
의견 감사합니다. README에 GitHub Pages 링크와 데모 이미지(gif)를 추가할 예정입니다.
